<?php

/**
 * Implements hook_theme().
 */
function ms_disclaimer_theme($existing, $type, $theme, $path) {
  return [
    'node__disclaimer__teaser' => [
      'template' => 'node--disclaimer--teaser',
      'base hook' => 'node'
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ms_disclaimer_preprocess_node(&$variables) {
  $variables['node'] = $variables['elements']['#node'];

  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['node'];

  // Pass node id to be able to get it in JS.
  $variables['#attached']['drupalSettings']['nid'] = $node->id();
}